### ISSUE TITLE
Backtracking on Write

### ISSUE THREAD

**Issue by JCumin** [JCumin/Brachylog#11]
Causes problems, there should be no unexplored branch points on that predicate.

**Comment by triska** [comment]
You can use [`setup_call_cleanup/3`](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/cleanup) to detect determinism, please see the [example](http://www.swi-prolog.org/pldoc/man?predicate=setup_call_cleanup/3).

This would be an awesome feature of Brachylog: Create side effects only when it is really safe!

**Comment by JCumin** [comment]
Fixed. It was actually a bug in the REPL that had extraneous choice points, not in `write`.
