### ISSUE TITLE
Move more of the implementation to Brachylog

### ISSUE THREAD

**Issue by triska** [JCumin/Brachylog#17]
Currently, Brachylog is implemented entirely in Prolog.

Prolog is certainly a nice implementation language, and using Prolog throughout also benefits the robustness of the underlying Prolog system. In this respect, the current implementation is very&nbsp;nice.

However, to benefit Brachylog itself, I think an effort should be made to write more of the primitives in&nbsp;**Brachylog**. Some of the current primitives can likely be expressed in terms of other, more general primitives. If that is not the case, such more general primitives are probably waiting to be discovered and should also be included in Brachylog.

In any case, it would be great if there were a controlled and convenient way to invoke subsets of Brachylog code from within its implementation.

**Comment by JCumin** [comment]
From I understand, I assume you want to write the built-in predicates in Brachylog itself?

While that sounds appealing, I see a few reasons why this would be difficult:
 - It would be much harder to maintain and extend (e.g. variables can only be one letter, you can't write comments, etc.)
 - It would impact the parsing phase: you can't manipulate atoms in Brachylog (which are used to distinguish variable types easily for example).
 - Predicates have automatic names, based on the order they appear in the code, which would make long code very hard to read.

**Comment by triska** [comment]
The way I think it could work and help is to have an easy and smooth way to call Brachylog snippets within the implementation of Brachylog. 

`term_expansion/2` and `goal_expansion/2` may help to replace such snippets with more elaborate calls at compilation time, if needed.

This way, I think some of the current language constructs could be defined in terms of Brachylog primitives in a quite self-contained and even readable way. 

Some candidates to try this approach could be for example:

- binary minus can be expressed within Brachylog as "negate, then add"
- "A greater than B" can be expressed as "B smaller than A"
- "head" and "behead" could maybe share a more general primitive "head_behead" (yielding a pair), usable from within Brachylog
- ...

**Comment by JCumin** [comment]
After thinking about it again, I will stay with the current full Prolog approach (though some built-ins use other built-ins), simply because the syntax/grammar/tokens of Brachylog are often evolving which would mean that one might have to change a lot of Brachylog code when updating those parts of the language, which is not the case when everything is in Prolog.

**Comment by triska** [comment]
Fair enough! Here is some material for inspiration though:

https://github.com/kragen/stoneknifeforth

Traditionally, bootstrapping a language in this way is a good test and display of its value and&nbsp;elegance, also if it only comes after the design stage. So, as a longer-term prospect, I hope you will reconsider this at some point in the&nbsp;future.
