### ISSUE TITLE
Infinite loop on `*` for completely free Input

### ISSUE THREAD

**Issue by kckennylau** [JCumin/Brachylog#29]

**Comment by JCumin** [comment]
This is actually due to a choice point that shouldn't exist and causes an infinite loop. The same thing happened on `2*4`, which is true but has another solution that loops infinitely

I will investigate further to fix this.

**Comment by JCumin** [comment]
@kckennylau The bug can be circumvented as such:

    .#$*3

Note that once the bug is fixed, it still wont behave as you say on a completely free variable, because `.*3` is true if `. = [3] / [1:3] / [_1:3] / etc.`, since you didn't specify that . must be a single integer.

**Comment by JCumin** [comment]
Fixed as of Brachylog v2 by removing overloading.
