### ISSUE TITLE
CLP(FD) support

### ISSUE THREAD

**Issue by JCumin** [JCumin/Brachylog#3]
Add support for the Constraint library CLP(FD) of Prolog.
The prefix `#` is available for this.
Possibly make all integer operations use  CLP(FD) by default.

**Comment by triska** [comment]
That would be awesome! CLP(FD) for all integer arithmetic would be really cool.

**Comment by JCumin** [comment]
With the new Prolog parser, all integer operations are CLPFD by default.

**Comment by triska** [comment]
Awesome work! Thank you!
