### ISSUE TITLE
Feature request: view generated code

### ISSUE THREAD

**Issue by kckennylau** [JCumin/Brachylog#31]
Maybe if we type -d as argument and turn on debug we will see the generated Prolog code.

**Comment by JCumin** [comment]
@kckennylau You can see the generated code when using Brachylog locally from SWI-Prolog's REPL. Both `run_from_atom` and `run_from_file` generate a file `compiled_brachylog.pl`

**Comment by kckennylau** [comment]
I am talking in TIO.
