### ISSUE TITLE
Feature request: prove from the most obvious

### ISSUE THREAD

**Issue by kckennylau** [JCumin/Brachylog#33]
I understand that this would be quite difficult to implement.

Let `x` and `y` be two predicates.

Currently, `?x.` and `.~x?` do the same.

However, `?xy.` and `.~y~x?` do not do the same. The latter is much more difficult to prove.

# My request

I request that if there are predicates that involve the input, they are to be proven first.

**Comment by JCumin** [comment]
This would break the left-to-right execution pattern and would make parsing (both by the parser and by a human) much more difficult and convoluted. I'm not sure this is even desirable in some situations where we want to check something using `?` AFTER other operations.

**Comment by triska** [comment]
Personally, I think this suggestion deserves a bit of reflection: For one thing, logical conjunctions can really be reordered freely. There is some precedent for such automated reordering for example in the [**Mercury**](https://www.mercurylang.org) programming language.

For example, see the [Semantics](https://www.mercurylang.org/information/doc-latest/mercury_ref/Semantics.html):

>  Conjunctions and function calls are “minimally” reordered as required by the modes ...

Note that this can in many cases occur without users even noticing. Figuring out the cases where such reordering can take place is of course the tough part for `Brachylog`.
