### ISSUE TITLE
N-chotomize is very slow

### ISSUE THREAD

**Issue by kckennylau** [JCumin/Brachylog#34]

**Comment by triska** [comment]
Could you please include a sample query (or program) that should run faster? Thank you!

**Comment by JCumin** [comment]
`@P@5` is pretty slow for example. The speed problem can be solved by moving the `append` call in the implementation of N-chotomize at the end of the rule. However it then causes extraneous buggy choice points that I need to look into more thoroughly.

**Comment by JCumin** [comment]
Fixed as of [this commit](https://github.com/JCumin/Brachylog/commit/9731508707a281ee233eb9f61650a1cd451631db) (though the fix is pretty ugly).
