### ISSUE TITLE
Subscripts for h and t

### ISSUE THREAD

**Issue by JCumin** [JCumin/Brachylog#43]
`h` and `t` should have subscripts such that e.g. `h₃` are the first 3 elements of its input, and `t₆` are the last 6 elements of its input (similar behavior to those of `b` and `k`).

**Comment by kckennylau** [comment]
The behaviours are not similar, since `h` returns a number while `h₃` would return an array. What should `h₁` return?

**Comment by JCumin** [comment]
@kckennylau `h₃` on `12345` would yield `123`, so still a number. Just like `h₃` on `"12345"` would yield `"123"` and on `[1,2,3,4,5]` we would get `[1,2,3]`.

`h₁` would work just like `h`, that is the default subscript for `h` is 1.

**Comment by kckennylau** [comment]
I mean, `h` on `[1,2,3,4,5]` would return `1` instead of `[1]`, right?

**Comment by JCumin** [comment]
@kckennylau  Right. So maybe `h` would give `1` and `h₁` would give `[1]`.

**Comment by JCumin** [comment]
After more than 2 years, I finally implemented it in [this commit](https://github.com/JCumin/Brachylog/commit/d2bb2b9b3549716456444bf7becb1480734f85ea). @kckennylau Patience!
