### ISSUE TITLE
Suggestion for random labeling

### ISSUE THREAD

**Issue by triska** [JCumin/Brachylog#51]
There is an (undocumented) labeling option called `random_value(+Seed)`, and you can use it to produce more or less *random* solutions while still retaining completeness.

For example:

<pre>
<b>?- X in 0..5, labeling([random_value(0)], [X]).</b>
X = 3 ;
X = 0 ;
X = 2 ;
X = 1 ;
X = 4 ;
X = 5.
</pre>

Note that the use of `Seed` makes this completely reproducible, and act like a true relation.

I say "more or less random" because the solutions are not produced in such a way that each of them is equally likely. Rather, only the choice of value for each individual variable is affected.

---

One possible use case:

https://codegolf.stackexchange.com/a/117529/18434

**Comment by JCumin** [comment]
This is pretty slow when the domain is big, and even overflows the stack when it's too big (e.g. find a random 8-digits number). I suppose it's not easily fixable?

**Comment by JCumin** [comment]
Implemented as of [this commit](https://github.com/JCumin/Brachylog/commit/7c4ac494f00eddf9fe108ef12f0dd1cd67e0ea56).

The predicate symbol is `≜₁`. This only works properly on finite domains, obviously.

```
?- run_from_atom('~lℕ≠≜₁',2,Z).
Z = 23 ;
Z = 48 ;
Z = 60 ;
Z = 80 ;
…
```

**Comment by triska** [comment]
It seems sufficiently efficient now, for example:

<pre>
?- time((<b>U #= 10^40</b>,
         X in 0..U,
         labeling([random_value(0)], [X]))).
<b>% 169 inferences, 0.000 CPU in 0.000 seconds (99% CPU, 344898 Lips)</b>
U = 10000000000000000000000000000000000000000,
X = <b>2474137494053817230546329383082252009579</b> ;
<b>% 91 inferences, 0.000 CPU in 0.000 seconds (91% CPU, 1338235 Lips)</b>
U = 10000000000000000000000000000000000000000,
X = <b>2410725425306837646409597099865362473338</b> ;
<b>% 95 inferences, 0.000 CPU in 0.000 seconds (91% CPU, 1319444 Lips)</b>
U = 10000000000000000000000000000000000000000,
X = <b>1920885495182001178851451470251780102139</b> ;
<b>% 103 inferences, 0.000 CPU in 0.000 seconds (90% CPU, 1450704 Lips)</b>
U = 10000000000000000000000000000000000000000,
X = <b>2436945892123923177527233981283594389902</b> .
</pre>

It is such use cases that help me to improve the constraint solver, so please let me know if you find any&nbsp;case that needs to become more efficient. Thank&nbsp;you!

**Comment by JCumin** [comment]
@triska Thanks, great improvement!

On that PPCG challenge, it now works well but seems to have pretty heavy variance on the execution time. I think this is caused by the "all digits are different" constraint though, because when I remove it it's pretty much instant:

```
?- time(run_from_atom('~lℕ≠≜₁',8,Z)).
% 11,155,871 inferences, 0.967 CPU in 0.984 seconds (98% CPU, 11534119 Lips)
Z = 92318046 .

?- time(run_from_atom('~lℕ≠≜₁',8,Z)).
% 454,873 inferences, 0.062 CPU in 0.070 seconds (89% CPU, 7289585 Lips)
Z = 80642917 .

?- time(run_from_atom('~lℕ≠≜₁',8,Z)).
% 6,884,540 inferences, 0.577 CPU in 0.583 seconds (99% CPU, 11927401 Lips)
Z = 10284359 .
```

Without `≠`:
```

 ?- time(run_from_atom('~lℕ≜₁',8,Z)).
% 115,501 inferences, 0.031 CPU in 0.040 seconds (78% CPU, 3701931 Lips)
Z = 45366017 ;
% 10,441 inferences, 0.016 CPU in 0.004 seconds (390% CPU, 669291 Lips)
Z = 16670246 ;
% 13,923 inferences, 0.000 CPU in 0.002 seconds (0% CPU, Infinite Lips)
Z = 18621401 
```

**Comment by triska** [comment]
I think one of the reasons here is that you are labeling the number as a whole instead of the list of digits. For example, I get much more uniform timings (but also less randomness on subsequent solutions) with the following patch:

<pre>
diff --git a/src/predicates.pl b/src/predicates.pl
index dd7e3d8..e423ed8 100644
--- a/src/predicates.pl
+++ b/src/predicates.pl
@@ -679,12 +679,13 @@ brachylog_different('default', [], []).
 brachylog_different('default', [H|T], [H|T]) :-
     maplist(prepend_integer, L, [H|T]),
     all_distinct(L).
-brachylog_different('default', 'integer':I, 'integer':I) :-
+brachylog_different('default', 'integer':I, Out) :-
     (   integer_value('integer':_:[_], I) ->
-        true
+        Out = integer:I
     ;   H #\= 0,
         integer_value('integer':_:[H,H2|T], I),
-        all_distinct([H,H2|T])
+        all_distinct([H,H2|T]),
+        Out = [H,H2|T]
     ).
 </pre>

Please note that I have not looked into this patch in detail, so please carefully review it before applying.

An alternative way out may be to strengthen or more efficiently implement the linking constraints between the whole number and its digits, so that the search space can be pruned more effectively.
