### ISSUE TITLE
Meta-predicates to map a predicate only over its input.

### ISSUE THREAD

**Issue by m-ender** [JCumin/Brachylog#57]
As discussed in chat:

> It seems like meta-predicates of the form "All elements of ? satisfy the predicate with ." and "Any element of ? satisfies the predicate with ." could be useful.

And while we're at it, maybe "no elements of ? ..." as well.

**Comment by JCumin** [comment]
This is implemented as of [this commit](https://github.com/JCumin/Brachylog/commit/de96abe002b51c1ef18d200ea1685cc9356bc36e). The meta-predicates are `ᵛ - verify`, `ᵉ - existence` and `ⁿ - nonexistence`.
