### ISSUE TITLE
√İ throws an exception on false

### ISSUE THREAD

**Issue by xash** [JCumin/Brachylog#69]
[√İ (TIO)](https://tio.run/##SypKTM6ozMlPN/r//1HHrCMb/v83NPofBQA)

    ERROR: -g consult('/opt/brachylog2/src/brachylog.pl'),run_from_files_no_file('.code.tio','.input.tio','.tmp.tio'):
    Type error: `integer' expected, found `3.4641016151377544' (a float)

… which kind of is correct, but this should just not unify. But works as expected if you put something in between like [√≡İ (TIO)](https://tio.run/##SypKTM6ozMlPN/r//1HHrEedC49s@P/f0Oh/FAA
)

**Comment by JCumin** [comment]
@xash Should be fixed as of [this commit](https://github.com/JCumin/Brachylog/commit/2efca3d804ee8a30c231bf5974d1e9d6dfae267c). Thanks!

Though note that this will not get pulled on TIO, as I think the maintainer is not very active these days.
