### ISSUE TITLE
Scoped variables

### ISSUE THREAD

**Issue by anka-213** [JCumin/Brachylog#70]
I would like to have some way of having variables declared in a predicate be available inside an inline predicate as well.

For example, say I want to add a number `A` to each element of a list `L`. A naive implementation might look like this:

```
[A,L]∧L{+↙A}ᵐ
```

However, this will not work, since `A` is a new variable local to the inline predicate. I would like a way to make it available inside the inline predicate.

In this specific case, I can write it as

```
[A,L]∧L+ᵐ↙A
```

but that won't work for more complicated cases, since custom predicates can't access subscripts (AFAIK).

On a closely related note: Is there any other way of mapping over a predicate and supplying a fixed value to each operation like this? Global variables wouldn't work for me, since this predicate is inside another loop.

**Comment by anka-213** [comment]
I managed to figure out that you can use

```
[A,L]∧Ag;Lz{[A,X]∧X+↙A}ᵐ
```

as a workaround.

Or if `A` is a scalar as in this example (but not in my actual use case [here](https://codegolf.stackexchange.com/a/239877/29859)):

```
z{[A,X]∧X+↙A}ᵐ
```

**Comment by JCumin** [comment]
[You can declare global variables in Brachylog, using superscripts](https://github.com/JCumin/Brachylog/wiki/2\)-Types-and-Variables#global-variables).

In your example, this would look like this: [`[A⁰,L]∧L{+↙A⁰}ᵐ`](https://tio.run/##SypKTM6ozMlPN/r/P9rxUeMGHZ/YRx3Lfaq1H7XNBPFrH26dAJQy1Yk21DGKjf0fBQA)

You used it in your Code Golf answer, so I’m not sure if I understand your issue.

**Comment by anka-213** [comment]
My issue is that if I declare it as global, it can't have different values. I should have given a better example with nested loops. For example, [this doesn't work](https://tio.run/##SypKTM6ozMlPN/r/vzra8VHjBh2f2Ecdy32qtR@1zQTxax9unQDC//9HRxvqRBvpGOuYxMaCGNFg1v8oAA):

```
{[A⁰,L]∧L{+↙A⁰}ᵐ}ᵐ
```
Input:
```
[[1,[2,3,4]],[2,[3,4]]
```
Output:
```
false.
```
Desired output:
```
Z = [[3,4,5],[5,6]]
```

So what I want is for the A to have a semi-local scope where it is valid only for the two inner predicates, not globally. Alternatively, for it to be valid for a whole line, but not globally, so I could write it something like this:

```
↰ᵐ↙1
[Aˢ,L]∧L{+↙Aˢ}ᵐ
```

**Comment by JCumin** [comment]
I see, it is clearer in this example.

There is no mechanism to do this, and unfortunately I have had no interest in working on Brachylog for quite some time now.

I’m not sure what solution could be used anyway. I like to maintain "logicness" of notations in Brachylog, and I don’t see an obvious notation to use for sharing variables between certain scopes only.

If you see a solution, and are willing to implement it, I would gladly merge it with the current version of Brachylog. You can also fork the language if you feel like it.

**Comment by anka-213** [comment]
I see! Thanks for your replies!
